trigger:
  branches:
    include:
      - master

pool:
  name: 'QuizAgentPool'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    # Install .NET SDK
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 8.x'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    
    # Restore NuGet packages
    - script: dotnet restore **/*.csproj
      displayName: 'Restore NuGet packages-shashi'

    # Build the project
    - script: dotnet build QuizApp/QuizApp.csproj --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Project'

    # Publish output artifacts
    - script: |
        dotnet publish QuizApp/QuizApp.csproj \
        --configuration Release \
        --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Artifacts'

    # Publish artifacts to pipeline
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

