trigger:
- master

pool:
  name: "VBQuizPool"

variables:
  imageName: 'quizapp'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Publish
  jobs:
  - job: Build
    displayName: Build .NET and publish artifact
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: |
        dotnet restore QuizApp/QuizApp.csproj
        dotnet publish QuizApp/QuizApp.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish
      displayName: 'Build and publish project'

    - script: |
        cp QuizApp/Dockerfile $(Build.ArtifactStagingDirectory)/
      displayName: 'Copy Dockerfile to artifact folder'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Docker
  displayName: Build and Push Docker Image
  dependsOn: Build
  jobs:
  - job: Docker
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      displayName: Build and Push to ACR
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: 'QuizApp/Dockerfile'
        containerRegistry: 'MyACRServiceConnection'  # replace with your ACR connection name
        tags: |
          latest
          $(tag)
