trigger:
  branches:
    include:
      - master

pool:
  name: 'QuizAgentPool'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    # Install .NET SDK
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '6.x'
    
    # Restore NuGet packages
    - script: dotnet restore /QuizApp/QuizApp.csproj
      displayName: 'Restore NuGet packages-shashi'

    # Build the project
    - script: dotnet build https://github.com/azureClassesOct2025/Quiz/tree/master/QuizApp/QuizApp.csproj --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Project'

    # Run tests (optional)
    - script: dotnet test demoapp/demoapp.web/tests --configuration $(buildConfiguration) --no-build --verbosity normal
      displayName: 'Run Tests'

    # Publish output artifacts
    - script: |
        dotnet publish Quiz/QuizApp/QuizApp.csproj \
        # dotnet publish demoapp/demoapp.web/demoapp.web.csproj \
          --configuration $(buildConfiguration) \
          --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Artifacts'

    # Publish artifacts to pipeline
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
